#![allow(clippy::useless_transmute)] // Generated by qmetaobject's Qt bridge.

use std::{
    io::Write,
    sync::{
        Arc,
        atomic::{AtomicU64, Ordering},
    },
    time::Duration,
};

use qmetaobject::prelude::*;
use qmetaobject::queued_callback;
use serde::Serialize;
use tempfile::TempPath;
use tokio::sync::mpsc;
use uuid::Uuid;

use flow_core::{
    language::{self, Plan},
    model::{
        AzureVoiceMode, DEFAULT_LANGUAGE_ROUTE_ID, HotKeyPreset, LanguageRoute,
        MAXIMUM_SELECTION_CHARACTERS, SameSelectionAction, Settings, SpeechSource, language_base,
    },
};

use crate::{
    azure::{self, AzureVoice},
    google::{self, GoogleVoice},
    selection, settings, shortcuts,
    system_speech::{self, SystemVoice},
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum PlaybackState {
    Hidden,
    Preparing,
    Playing,
    Paused,
    AwaitingRoute,
    Finished,
    Message,
}

impl PlaybackState {
    const fn id(self) -> &'static str {
        match self {
            Self::Hidden => "hidden",
            Self::Preparing => "preparing",
            Self::Playing => "playing",
            Self::Paused => "paused",
            Self::AwaitingRoute => "awaitingRoute",
            Self::Finished => "finished",
            Self::Message => "message",
        }
    }
}

struct CloudSegment {
    audio: TempPath,
    duration_ms: u64,
    word_timings: Vec<google::WordTiming>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct Snapshot<'a> {
    settings: &'a Settings,
    supported_languages: &'static [(&'static str, &'static str)],
    system_voices: &'a [SystemVoice],
    azure_voices: &'a [AzureVoice],
    google_voices: &'a [GoogleVoice],
}

#[derive(QObject)]
pub struct FlowBackend {
    base: qt_base_class!(trait QObject),

    state: qt_property!(QString; NOTIFY state_changed),
    state_changed: qt_signal!(),
    popup_visible: qt_property!(bool; NOTIFY popup_visible_changed),
    popup_visible_changed: qt_signal!(),
    message: qt_property!(QString; NOTIFY message_changed),
    message_changed: qt_signal!(),
    playback_text: qt_property!(QString; NOTIFY playback_text_changed),
    playback_text_changed: qt_signal!(),
    snapshot_json: qt_property!(QString; NOTIFY snapshot_json_changed),
    snapshot_json_changed: qt_signal!(),
    detected_languages_json: qt_property!(QString; NOTIFY detected_languages_json_changed),
    detected_languages_json_changed: qt_signal!(),
    text_language_override: qt_property!(QString; NOTIFY text_language_override_changed),
    text_language_override_changed: qt_signal!(),
    override_needs_route: qt_property!(bool; NOTIFY override_needs_route_changed),
    override_needs_route_changed: qt_signal!(),
    manual_route_needed: qt_property!(bool; NOTIFY manual_route_needed_changed),
    manual_route_needed_changed: qt_signal!(),
    manual_route_sentence_text: qt_property!(QString; NOTIFY manual_route_sentence_text_changed),
    manual_route_sentence_text_changed: qt_signal!(),
    shortcut_status: qt_property!(QString; NOTIFY shortcut_status_changed),
    shortcut_status_changed: qt_signal!(),
    configuration_error: qt_property!(QString; NOTIFY configuration_error_changed),
    configuration_error_changed: qt_signal!(),

    play_cloud: qt_signal!(file_url: QString, word_timings_json: QString, offset_ms: i64),
    seek_audio: qt_signal!(offset_ms: i64),
    pause_playback: qt_signal!(),
    resume_playback: qt_signal!(),
    stop_audio: qt_signal!(),
    show_settings: qt_signal!(),

    playback_progress: qt_property!(f64; NOTIFY playback_progress_changed),
    playback_progress_changed: qt_signal!(),
    playback_seek_supported: qt_property!(bool; NOTIFY playback_seek_supported_changed),
    playback_seek_supported_changed: qt_signal!(),

    start: qt_method!(
        fn start(&mut self) {
            self.start_services();
        }
    ),
    read_selection: qt_method!(
        fn read_selection(&mut self) {
            self.request_selection();
        }
    ),
    open_settings: qt_method!(
        fn open_settings(&self) {
            self.show_settings();
        }
    ),
    pause_or_resume: qt_method!(
        fn pause_or_resume(&mut self) {
            self.toggle_pause();
        }
    ),
    stop: qt_method!(
        fn stop(&mut self) {
            self.stop_reading();
        }
    ),
    playback_finished: qt_method!(
        fn playback_finished(&mut self) {
            self.cloud_segment_finished();
        }
    ),
    playback_failed: qt_method!(
        fn playback_failed(&mut self, error: QString) {
            self.show_message(error.to_string());
        }
    ),
    set_route_for_language: qt_method!(
        fn set_route_for_language(&mut self, language_tag: QString, route_id: QString) {
            let Ok(route_id) = Uuid::parse_str(&route_id.to_string()) else {
                return;
            };
            let Some(route) = self
                .settings
                .all_language_routes()
                .into_iter()
                .find(|route| route.id == route_id)
            else {
                return;
            };
            let tag = language_tag.to_string();
            let Some(mut plan) = self.plan.take() else {
                return;
            };
            for sentence in plan.sentences.iter_mut() {
                if sentence.detected_language_tag.as_deref() == Some(tag.as_str()) {
                    sentence.route = route.clone();
                    sentence.needs_review = false;
                }
            }
            self.plan = Some(plan.clone());
            self.start_plan(self.selected_text.clone(), plan);
        }
    ),
    set_text_language_override: qt_method!(
        fn set_text_language_override(&mut self, language_tag: QString) {
            let tag = language_tag.to_string();
            let tag = if tag.is_empty() { None } else { Some(tag) };
            if tag == self.text_language_override {
                return;
            }
            self.text_language_override = tag.clone();
            self.text_language_override_changed();
            self.refresh_override_needs_route();
            match (self.playback_state, &tag) {
                (
                    PlaybackState::Preparing
                    | PlaybackState::Playing
                    | PlaybackState::Paused
                    | PlaybackState::AwaitingRoute,
                    Some(tag),
                ) => {
                    if self.selected_text.is_empty() {
                        return;
                    }
                    let plan =
                        language::plan_with_override(&self.selected_text, &self.settings, Some(tag));
                    if self.override_needs_route {
                        // Never speak with a guessed voice: hold playback
                        // until a route is chosen for this language.
                        self.cancel_dismiss();
                        self.stop_active_playback();
                        self.plan = Some(plan);
                        self.refresh_detected_languages();
                        self.set_state(PlaybackState::AwaitingRoute);
                        self.set_popup_visible(true);
                    } else {
                        self.start_plan(self.selected_text.clone(), plan);
                    }
                }
                (
                    PlaybackState::Preparing
                    | PlaybackState::Playing
                    | PlaybackState::Paused
                    | PlaybackState::AwaitingRoute,
                    None,
                ) => {
                    if self.selected_text.is_empty() {
                        return;
                    }
                    let plan = language::plan(&self.selected_text, &self.settings);
                    self.start_auto_plan(self.selected_text.clone(), plan);
                }
                _ => {}
            }
        }
    ),
    set_override_route: qt_method!(
        fn set_override_route(&mut self, route_id: QString) {
            if self.text_language_override.is_none() && !self.manual_route_needed {
                return;
            }
            let Ok(route_id) = Uuid::parse_str(&route_id.to_string()) else {
                return;
            };
            let route = self
                .settings
                .all_language_routes()
                .into_iter()
                .find(|route| route.id == route_id);
            let Some(route) = route else {
                return;
            };
            let Some(mut plan) = self.plan.take() else {
                return;
            };
            if self.text_language_override.is_some() {
                for sentence in plan.sentences.iter_mut() {
                    sentence.route = route.clone();
                    sentence.needs_review = false;
                }
                self.manual_route_needed = false;
                self.manual_route_needed_changed();
                self.plan = Some(plan.clone());
                self.start_plan(self.selected_text.clone(), plan);
                return;
            }

            let Some(sentence) = plan.sentences.iter_mut().find(|sentence| sentence.needs_review) else {
                return;
            };
            sentence.route = route;
            sentence.needs_review = false;
            if plan.needs_language_check() {
                self.plan = Some(plan);
                self.refresh_detected_languages();
                return;
            }
            self.manual_route_needed = false;
            self.manual_route_needed_changed();
            self.plan = Some(plan.clone());
            self.start_plan(self.selected_text.clone(), plan);
        }
    ),
    update_setting: qt_method!(
        fn update_setting(&mut self, key: QString, value: QString) {
            self.apply_setting(&key.to_string(), &value.to_string());
        }
    ),
    add_language: qt_method!(
        fn add_language(&mut self, language_tag: QString) {
            self.add_language_route(&language_tag.to_string());
        }
    ),
    remove_language: qt_method!(
        fn remove_language(&mut self, route_id: QString) {
            if let Ok(id) = Uuid::parse_str(&route_id.to_string()) {
                self.settings.language_routes.retain(|route| route.id != id);
                self.persist_settings();
            }
        }
    ),
    update_route: qt_method!(
        fn update_route(&mut self, route_id: QString, field: QString, value: QString) {
            self.apply_route_setting(
                &route_id.to_string(),
                &field.to_string(),
                &value.to_string(),
            );
        }
    ),
    save_azure_configuration: qt_method!(
        fn save_azure_configuration(&mut self, endpoint: QString, subscription_key: QString) {
            self.save_azure(&endpoint.to_string(), &subscription_key.to_string());
        }
    ),
    clear_azure_configuration: qt_method!(
        fn clear_azure_configuration(&mut self) {
            azure::clear_key();
            self.settings.azure_endpoint = None;
            self.azure_voices.clear();
            if self.settings.speech_source == SpeechSource::Azure {
                self.settings.speech_source = SpeechSource::System;
            }
            self.persist_settings();
        }
    ),
    refresh_azure_voices: qt_method!(
        fn refresh_azure_voices(&mut self) {
            self.load_azure_voices();
        }
    ),
    save_google_configuration: qt_method!(
        fn save_google_configuration(&mut self, api_key: QString) {
            self.save_google(&api_key.to_string());
        }
    ),
    clear_google_configuration: qt_method!(
        fn clear_google_configuration(&mut self) {
            google::clear_key();
            self.settings.google_api_key_configured = false;
            self.google_voices.clear();
            if self.settings.speech_source == SpeechSource::Google {
                self.settings.speech_source = SpeechSource::System;
            }
            self.persist_settings();
        }
    ),
    refresh_google_voices: qt_method!(
        fn refresh_google_voices(&mut self) {
            self.load_google_voices();
        }
    ),
    play_test_voice: qt_method!(
        fn play_test_voice(&mut self) {
            let text = "Flow is ready to read selected text.".to_owned();
            let plan = language::single_sentence(&text, &self.settings);
            self.start_plan(text, plan);
        }
    ),
    seek_to_fraction: qt_method!(
        fn seek_to_fraction(&mut self, fraction: f64) {
            self.seek_cloud(fraction);
        }
    ),
    report_position: qt_method!(
        fn report_position(&mut self, position_ms: i64) {
            self.update_cloud_progress(position_ms.max(0) as u64);
        }
    ),
    report_duration: qt_method!(
        fn report_duration(&mut self, duration_ms: i64) {
            if duration_ms <= 0 {
                return;
            }
            if let Some(segment) = self.cloud_segments.get_mut(self.cloud_current_segment) {
                segment.duration_ms = duration_ms as u64;
            }
        }
    ),

    settings: Settings,
    playback_state: PlaybackState,
    selected_text: String,
    playback_text: QString,
    plan: Option<Plan>,
    text_language_override: Option<String>,
    override_needs_route: bool,
    manual_route_needed: bool,
    system_voices: Vec<SystemVoice>,
    azure_voices: Vec<AzureVoice>,
    google_voices: Vec<GoogleVoice>,
    cloud_segments: Vec<CloudSegment>,
    cloud_current_segment: usize,
    shortcut_commands: Option<mpsc::UnboundedSender<shortcuts::Command>>,
    system_speech_commands: Option<std::sync::mpsc::Sender<system_speech::Command>>,
    services_started: bool,
    selection_generation: Arc<AtomicU64>,
    dismiss_generation: Arc<AtomicU64>,
    playback_generation: Arc<AtomicU64>,
}

impl Default for FlowBackend {
    fn default() -> Self {
        let settings = settings::load();
        let snapshot_json = serialize(&Snapshot {
            settings: &settings,
            supported_languages: language::supported_languages(),
            system_voices: &[],
            azure_voices: &[],
            google_voices: &[],
        });
        Self {
            base: Default::default(),
            state: PlaybackState::Hidden.id().into(),
            state_changed: Default::default(),
            popup_visible: false,
            popup_visible_changed: Default::default(),
            message: QString::default(),
            message_changed: Default::default(),
            playback_text: QString::default(),
            playback_text_changed: Default::default(),
            snapshot_json: snapshot_json.into(),
            snapshot_json_changed: Default::default(),
            detected_languages_json: "[]".into(),
            detected_languages_json_changed: Default::default(),
            text_language_override: QString::default(),
            text_language_override_changed: Default::default(),
            override_needs_route: false,
            override_needs_route_changed: Default::default(),
            manual_route_needed: false,
            manual_route_needed_changed: Default::default(),
            manual_route_sentence_text: QString::default(),
            manual_route_sentence_text_changed: Default::default(),
            shortcut_status: "Registering global shortcut…".into(),
            shortcut_status_changed: Default::default(),
            configuration_error: QString::default(),
            configuration_error_changed: Default::default(),
            playback_progress: 0.0,
            playback_progress_changed: Default::default(),
            playback_seek_supported: false,
            playback_seek_supported_changed: Default::default(),
            play_cloud: Default::default(),
            seek_audio: Default::default(),
            pause_playback: Default::default(),
            resume_playback: Default::default(),
            stop_audio: Default::default(),
            show_settings: Default::default(),
            start: Default::default(),
            read_selection: Default::default(),
            open_settings: Default::default(),
            pause_or_resume: Default::default(),
            stop: Default::default(),
            playback_finished: Default::default(),
            playback_failed: Default::default(),
            set_route_for_language: Default::default(),
            set_text_language_override: Default::default(),
            set_override_route: Default::default(),
            update_setting: Default::default(),
            add_language: Default::default(),
            remove_language: Default::default(),
            update_route: Default::default(),
            save_azure_configuration: Default::default(),
            clear_azure_configuration: Default::default(),
            refresh_azure_voices: Default::default(),
            save_google_configuration: Default::default(),
            clear_google_configuration: Default::default(),
            refresh_google_voices: Default::default(),
            play_test_voice: Default::default(),
            seek_to_fraction: Default::default(),
            report_position: Default::default(),
            report_duration: Default::default(),
            settings,
            playback_state: PlaybackState::Hidden,
            selected_text: String::new(),
            playback_text: QString::default(),
            plan: None,
            text_language_override: None,
            override_needs_route: false,
            manual_route_needed: false,
            manual_route_sentence_text: QString::default(),
            system_voices: Vec::new(),
            azure_voices: Vec::new(),
            google_voices: Vec::new(),
            cloud_segments: Vec::new(),
            cloud_current_segment: 0,
            playback_progress: 0.0,
            playback_seek_supported: false,
            shortcut_commands: None,
            shortcut_commands: None,
            system_speech_commands: None,
            services_started: false,
            selection_generation: Arc::new(AtomicU64::new(0)),
            dismiss_generation: Arc::new(AtomicU64::new(0)),
            playback_generation: Arc::new(AtomicU64::new(0)),
        }
    }
}

impl FlowBackend {
    fn start_services(&mut self) {
        if self.services_started {
            return;
        }
        self.services_started = true;

        let (sender, receiver) = mpsc::unbounded_channel();
        self.shortcut_commands = Some(sender);
        let activation_pointer = QPointer::from(&*self);
        let activated = queued_callback(move |()| {
            if let Some(backend) = activation_pointer.as_pinned() {
                backend.borrow_mut().request_selection();
            }
        });
        let status_pointer = QPointer::from(&*self);
        let status = queued_callback(move |message: String| {
            if let Some(backend) = status_pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                backend.shortcut_status = message.into();
                backend.shortcut_status_changed();
            }
        });
        let preset = self.settings.hot_key;
        std::thread::spawn(move || {
            let runtime = tokio::runtime::Runtime::new().expect("Flow can create an async runtime");
            runtime.block_on(shortcuts::run(
                preset,
                receiver,
                shortcuts::Callbacks { activated, status },
            ));
        });

        let voices_pointer = QPointer::from(&*self);
        let voices_changed = queued_callback(move |voices: Vec<SystemVoice>| {
            if let Some(backend) = voices_pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                backend.system_voices = voices;
                backend.refresh_snapshot();
            }
        });
        let finished_pointer = QPointer::from(&*self);
        let finished_generation = Arc::clone(&self.playback_generation);
        let finished = queued_callback(move |generation: u64| {
            if finished_generation.load(Ordering::SeqCst) != generation {
                return;
            }
            if let Some(backend) = finished_pointer.as_pinned() {
                backend.borrow_mut().finish_reading();
            }
        });
        let failed_pointer = QPointer::from(&*self);
        let failed_generation = Arc::clone(&self.playback_generation);
        let failed = queued_callback(move |(generation, message): (u64, String)| {
            if failed_generation.load(Ordering::SeqCst) != generation {
                return;
            }
            if let Some(backend) = failed_pointer.as_pinned() {
                backend.borrow_mut().show_message(message);
            }
        });
        self.system_speech_commands = Some(system_speech::start(system_speech::Callbacks {
            voices_changed: Box::new(voices_changed),
            finished: Box::new(finished),
            failed: Box::new(failed),
        }));

        if self.settings.azure_endpoint.is_some() {
            self.load_azure_voices();
        }
        if self.settings.google_api_key_configured {
            self.load_google_voices();
        }
    }

    fn request_selection(&mut self) {
        let request_id = self.selection_generation.fetch_add(1, Ordering::SeqCst) + 1;
        if selection::debug_enabled() {
            eprintln!("[Flow selection] request {request_id} received");
        }
        let generation = Arc::clone(&self.selection_generation);
        let pointer = QPointer::from(&*self);
        let deliver = queued_callback(move |result: Result<String, String>| {
            if generation.load(Ordering::SeqCst) != request_id {
                return;
            }
            if let Some(backend) = pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                match result {
                    Ok(text) => backend.handle_selection(text),
                    Err(message) => backend.show_message(message),
                }
            }
        });
        std::thread::spawn(move || {
            let runtime = tokio::runtime::Runtime::new().expect("Flow can create an async runtime");
            let result = runtime
                .block_on(selection::read_focused_selection())
                .map_err(|error| error.to_string());
            if selection::debug_enabled() {
                match &result {
                    Ok(text) => eprintln!(
                        "[Flow selection] request {request_id} resolved ({} characters)",
                        text.chars().count()
                    ),
                    Err(error) => {
                        eprintln!("[Flow selection] request {request_id} failed: {error}")
                    }
                }
            }
            deliver(result);
        });
    }

    fn handle_selection(&mut self, text: String) {
        // The override lasts until the next capture only.
        let had_language_override = self.text_language_override.is_some();
        self.text_language_override = None;
        self.text_language_override_changed();
        self.refresh_override_needs_route();

        let normalized = normalize(&text);
        if normalized.is_empty() {
            self.show_message(format!(
                "Select some text, then press {}.",
                self.settings.hot_key.title()
            ));
            return;
        }
        if normalized.chars().count() > MAXIMUM_SELECTION_CHARACTERS {
            self.show_message("This selection is longer than Flow's 10-minute reading limit.");
            return;
        }
        if normalized == normalize(&self.selected_text)
            && self.settings.same_selection_action == SameSelectionAction::PauseResume
            && matches!(
                self.playback_state,
                PlaybackState::Playing | PlaybackState::Paused
            )
            && !had_language_override
        {
            self.toggle_pause();
            return;
        }

        // Resetting an override requires a new Auto plan, so replay this
        // selection instead of resuming the old overridden plan.
        let plan = language::plan(&text, &self.settings);
        self.start_auto_plan(text, plan);
    }

    fn start_auto_plan(&mut self, text: String, plan: Plan) {
        if !plan.needs_language_check() {
            self.manual_route_needed = false;
            self.manual_route_needed_changed();
            self.start_plan(text, plan);
            return;
        }
        self.cancel_dismiss();
        self.stop_active_playback();
        self.selected_text = text;
        self.playback_text = playback_text(&plan, &text).into();
        self.playback_text_changed();
        self.plan = Some(plan);
        self.manual_route_needed = true;
        self.manual_route_needed_changed();
        self.refresh_detected_languages();
        self.set_state(PlaybackState::AwaitingRoute);
        self.set_popup_visible(true);
    }

    fn refresh_detected_languages(&mut self) {
        let mut tags: Vec<String> = Vec::new();
        if let Some(plan) = &self.plan {
            for sentence in &plan.sentences {
                if let Some(tag) = &sentence.detected_language_tag {
                    if !tags.contains(tag) {
                        tags.push(tag.clone());
                    }
                }
            }
        }
        self.detected_languages_json =
            serde_json::to_string(&tags).unwrap_or_else(|_| "[]".into()).into();
        self.detected_languages_json_changed();
        self.manual_route_sentence_text = self
            .plan
            .as_ref()
            .and_then(|plan| plan.sentences.iter().find(|sentence| sentence.needs_review))
            .map(|sentence| sentence.text.clone())
            .unwrap_or_default()
            .into();
        self.manual_route_sentence_text_changed();
    }

    fn refresh_override_needs_route(&mut self) {
        let unrouted = self
            .text_language_override
            .as_deref()
            .is_some_and(|tag| self.settings.language_route(tag).is_none());
        if self.override_needs_route != unrouted {
            self.override_needs_route = unrouted;
            self.override_needs_route_changed();
        }
    }

    fn start_plan(&mut self, text: String, plan: Plan) {
        self.cancel_dismiss();
        self.stop_active_playback();
        if self.manual_route_needed {
            self.manual_route_needed = false;
            self.manual_route_needed_changed();
        }
        self.selected_text = text;
        self.playback_text = playback_text(&plan, &text).into();
        self.playback_text_changed();
        self.plan = Some(plan.clone());
        self.refresh_detected_languages();
        self.set_state(PlaybackState::Preparing);
        self.set_popup_visible(true);
        let generation = self.playback_generation.fetch_add(1, Ordering::SeqCst) + 1;

        match self.settings.speech_source {
            SpeechSource::System => {
                self.set_state(PlaybackState::Playing);
                let sent = self.system_speech_commands.as_ref().is_some_and(|sender| {
                    sender
                        .send(system_speech::Command::Play { generation, plan })
                        .is_ok()
                });
                if !sent {
                    self.show_message("Flow could not start the system speech service.");
                }
            }
            SpeechSource::Azure => self.synthesize_azure(plan, generation),
            SpeechSource::Google => self.synthesize_google(plan, generation),
        }
    }

    fn synthesize_azure(&mut self, plan: Plan, generation: u64) {
        let Some(endpoint) = self.settings.azure_endpoint.clone() else {
            self.show_message("Set up Azure Speech before choosing Azure voice.");
            return;
        };
        let settings = self.settings.clone();
        let current_generation = Arc::clone(&self.playback_generation);
        let pointer = QPointer::from(&*self);
        let deliver = queued_callback(move |result: Result<Vec<(Vec<u8>, Vec<google::WordTiming>)>, String>| {
            if current_generation.load(Ordering::SeqCst) != generation {
                return;
            }
            if let Some(backend) = pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                match result {
                    Ok(audio) => backend.play_cloud_audio(audio, 160_000),
                    Err(message) => backend.show_message(message),
                }
            }
        });
        std::thread::spawn(move || {
            let result = azure::load_key()
                .and_then(|key| azure::synthesize(&endpoint, &key, &plan, &settings))
                .map(|audio| vec![(audio, Vec::new())])
                .map_err(|_| {
                    "Azure could not synthesize this selection. Check the endpoint, key, and voice."
                        .to_owned()
                });
            deliver(result);
        });
    }

    fn synthesize_google(&mut self, plan: Plan, generation: u64) {
        if !self.settings.google_api_key_configured {
            self.show_message("Set up Google Cloud Text-to-Speech before choosing Google voice.");
            return;
        }
        let current_generation = Arc::clone(&self.playback_generation);
        let settings = self.settings.clone();
        let pointer = QPointer::from(&*self);
        let deliver = queued_callback(move |result: Result<Vec<(Vec<u8>, Vec<google::WordTiming>)>, String>| {
            if current_generation.load(Ordering::SeqCst) != generation {
                return;
            }
            if let Some(backend) = pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                match result {
                    Ok(audio) => backend.play_cloud_audio(audio, 32_000),
                    Err(message) => backend.show_message(message),
                }
            }
        });
        std::thread::spawn(move || {
            let result = google::load_key()
                .and_then(|key| google::synthesize(&key, &plan, settings.word_highlighting_enabled))
                .map(|segments| segments.into_iter().map(|segment| (segment.audio, segment.word_timings)).collect())
                .map_err(|_| {
                    "Google Cloud could not synthesize this selection. Check the API key and voice."
                        .to_owned()
                });
            deliver(result);
        });
    }

    fn play_cloud_audio(&mut self, audio_segments: Vec<(Vec<u8>, Vec<google::WordTiming>)>, bits_per_second: u64) {
        let segments = audio_segments
            .into_iter()
            .map(|(audio, word_timings)| {
                tempfile::Builder::new()
                    .prefix("flow-")
                    .suffix(".mp3")
                    .tempfile()
                    .and_then(|mut file| {
                        file.write_all(&audio)?;
                        let duration_ms = (audio.len() as u64)
                            .saturating_mul(8_000)
                            .checked_div(bits_per_second.max(1))
                            .unwrap_or(0);
                        Ok(CloudSegment {
                            audio: file.into_temp_path(),
                            duration_ms,
                            word_timings,
                        })
                    })
            })
            .collect::<Result<Vec<_>, _>>();
        match segments {
            Ok(segments) if !segments.is_empty() => {
                self.cloud_segments = segments;
                self.cloud_current_segment = 0;
                if !self.playback_seek_supported {
                    self.playback_seek_supported = true;
                    self.playback_seek_supported_changed();
                }
                self.start_cloud_segment(0, 0);
            }
            _ => self
                .show_message("The cloud speech service returned audio that Flow could not play."),
        }
    }

    fn start_cloud_segment(&mut self, index: usize, offset_ms: i64) {
        let Some(segment) = self.cloud_segments.get(index) else {
            self.finish_reading();
            return;
        };
        self.cloud_current_segment = index;
        let url = format!("file://{}", segment.audio.display());
        let timings_json = serde_json::to_string(&segment.word_timings).unwrap_or_else(|_| "[]".into());
        self.set_state(PlaybackState::Playing);
        self.play_cloud(url.into(), timings_json.into(), offset_ms);
    }

    fn cloud_segment_finished(&mut self) {
        if !matches!(
            self.playback_state,
            PlaybackState::Playing | PlaybackState::Paused
        ) {
            return;
        }
        self.start_cloud_segment(self.cloud_current_segment + 1, 0);
    }

    fn seek_cloud(&mut self, fraction: f64) {
        if !self.playback_seek_supported || self.cloud_segments.is_empty() {
            return;
        }
        let total_ms: u64 = self.cloud_segments.iter().map(|s| s.duration_ms).sum();
        if total_ms == 0 {
            return;
        }
        let clamped = fraction.clamp(0.0, 1.0);
        let mut remaining = (clamped * total_ms as f64).round() as i64;
        for (index, segment) in self.cloud_segments.iter().enumerate() {
            let duration = segment.duration_ms as i64;
            if remaining > duration && index < self.cloud_segments.len() - 1 {
                remaining -= duration;
                continue;
            }
            let within = remaining.clamp(0, duration);
            if index == self.cloud_current_segment {
                self.seek_audio(within);
                self.update_cloud_progress(within.max(0) as u64);
            } else {
                let was_paused = self.playback_state == PlaybackState::Paused;
                self.start_cloud_segment(index, within);
                if was_paused {
                    self.pause_playback();
                }
            }
            return;
        }
    }

    fn update_cloud_progress(&mut self, position_in_current_ms: u64) {
        let Some(current_duration) = self
            .cloud_segments
            .get(self.cloud_current_segment)
            .map(|segment| segment.duration_ms)
        else {
            return;
        };
        let total_ms: u64 = self.cloud_segments.iter().map(|s| s.duration_ms).sum();
        if total_ms == 0 {
            return;
        }
        let elapsed_before: u64 = self
            .cloud_segments
            .iter()
            .take(self.cloud_current_segment)
            .map(|segment| segment.duration_ms)
            .sum();
        let elapsed =
            elapsed_before + position_in_current_ms.min(current_duration);
        let progress = ((elapsed as f64 / total_ms as f64).clamp(0.0, 1.0) * 1000.0).round() / 1000.0;
        if (progress - self.playback_progress).abs() >= 0.001 {
            self.playback_progress = progress;
            self.playback_progress_changed();
        }
    }

    fn reset_cloud_timeline(&mut self) {
        self.cloud_segments.clear();
        self.cloud_current_segment = 0;
        if self.playback_seek_supported {
            self.playback_seek_supported = false;
            self.playback_seek_supported_changed();
        }
        if self.playback_progress != 0.0 {
            self.playback_progress = 0.0;
            self.playback_progress_changed();
        }
    }

    fn toggle_pause(&mut self) {
        match self.playback_state {
            PlaybackState::Playing => {
                if let Some(sender) = &self.system_speech_commands {
                    let _ = sender.send(system_speech::Command::Pause);
                }
                self.pause_playback();
                self.set_state(PlaybackState::Paused);
            }
            PlaybackState::Paused => {
                if let Some(sender) = &self.system_speech_commands {
                    let _ = sender.send(system_speech::Command::Resume);
                }
                self.resume_playback();
                self.set_state(PlaybackState::Playing);
            }
            _ => {}
        }
    }

    fn stop_reading(&mut self) {
        self.cancel_dismiss();
        self.stop_active_playback();
        self.selected_text.clear();
        self.plan = None;
        self.refresh_detected_languages();
        self.set_state(PlaybackState::Hidden);
        self.set_popup_visible(false);
    }

    fn stop_active_playback(&mut self) {
        self.playback_generation.fetch_add(1, Ordering::SeqCst);
        if let Some(sender) = &self.system_speech_commands {
            let _ = sender.send(system_speech::Command::Stop);
        }
        self.stop_audio();
        self.reset_cloud_timeline();
    }

    fn finish_reading(&mut self) {
        if !matches!(
            self.playback_state,
            PlaybackState::Playing | PlaybackState::Paused
        ) {
            return;
        }
        self.reset_cloud_timeline();
        self.set_state(PlaybackState::Finished);
        self.dismiss_after_delay();
    }

    fn show_message(&mut self, message: impl Into<String>) {
        self.cancel_dismiss();
        self.stop_active_playback();
        self.selected_text.clear();
        self.plan = None;
        self.refresh_detected_languages();
        self.message = message.into().into();
        self.message_changed();
        self.set_state(PlaybackState::Message);
        self.set_popup_visible(true);
        self.dismiss_after_delay();
    }

    fn dismiss_after_delay(&mut self) {
        let request_id = self.dismiss_generation.fetch_add(1, Ordering::SeqCst) + 1;
        let generation = Arc::clone(&self.dismiss_generation);
        let delay = self.settings.popup_dismiss_seconds.clamp(3.0, 30.0);
        let pointer = QPointer::from(&*self);
        let dismiss = queued_callback(move |()| {
            if generation.load(Ordering::SeqCst) != request_id {
                return;
            }
            if let Some(backend) = pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                backend.selected_text.clear();
                backend.plan = None;
                backend.set_state(PlaybackState::Hidden);
                backend.set_popup_visible(false);
            }
        });
        std::thread::spawn(move || {
            std::thread::sleep(Duration::from_secs_f64(delay));
            dismiss(());
        });
    }

    fn cancel_dismiss(&self) {
        self.dismiss_generation.fetch_add(1, Ordering::SeqCst);
    }

    fn add_language_route(&mut self, language_tag: &str) {
        let supported = language::supported_languages()
            .iter()
            .any(|(tag, _)| tag.eq_ignore_ascii_case(language_tag));
        let duplicate = self
            .settings
            .all_language_routes()
            .iter()
            .any(|route| language_base(&route.language_tag) == language_base(language_tag));
        if supported && !duplicate {
            let mut route = LanguageRoute::new(language_tag);
            route.system_voice_name = self
                .system_voices
                .iter()
                .find(|voice| language_base(&voice.language_tag) == language_base(language_tag))
                .map(|voice| voice.name.clone());
            route.azure_voice_name = self
                .azure_voices
                .iter()
                .find(|voice| {
                    language_base(&voice.locale) == language_base(language_tag)
                        || voice
                            .secondary_locales
                            .iter()
                            .any(|locale| language_base(locale) == language_base(language_tag))
                })
                .map(|voice| voice.short_name.clone())
                .or_else(|| Some(self.settings.azure_voice_name.clone()));
            route.google_voice_name = self
                .google_voices
                .iter()
                .find(|voice| {
                    voice
                        .language_codes
                        .iter()
                        .any(|locale| language_base(locale) == language_base(language_tag))
                })
                .map(|voice| voice.name.clone());
            route.azure_speech_rate = self.settings.azure_speech_rate;
            route.google_speech_rate = self.settings.google_speech_rate;
            self.settings.language_routes.push(route);
            self.persist_settings();
        }
    }

    fn apply_setting(&mut self, key: &str, value: &str) {
        let previous_hotkey = self.settings.hot_key;
        match key {
            "speechSource" => {
                self.settings.speech_source = match value {
                    "azure" => SpeechSource::Azure,
                    "google" => SpeechSource::Google,
                    _ => SpeechSource::System,
                };
                self.configuration_error = QString::default();
                self.configuration_error_changed();
            }
            "hotKey" => {
                self.settings.hot_key = match value {
                    "altSuperSpace" => HotKeyPreset::AltSuperSpace,
                    "controlAltR" => HotKeyPreset::ControlAltR,
                    _ => HotKeyPreset::AltSuperR,
                };
            }
            "systemVoiceName" => {
                self.settings.system_voice_name = nonempty(value);
            }
            "systemSpeechRate" => {
                if let Ok(rate) = value.parse::<f64>() {
                    self.settings.system_speech_rate = rate.clamp(-1.0, 1.0);
                }
            }
            "popupDismissSeconds" => {
                if let Ok(seconds) = value.parse::<f64>() {
                    self.settings.popup_dismiss_seconds = seconds.clamp(3.0, 30.0);
                }
            }
            "sameSelectionAction" => {
                self.settings.same_selection_action = if value == "restart" {
                    SameSelectionAction::Restart
                } else {
                    SameSelectionAction::PauseResume
                };
            }
            "wordHighlightingEnabled" => self.settings.word_highlighting_enabled = value == "true",
            "azureVoiceName" => self.settings.azure_voice_name = value.into(),
            "azureSpeechRate" => {
                if let Ok(rate) = value.parse::<f64>() {
                    self.settings.azure_speech_rate = rate.clamp(-1.0, 1.0);
                }
            }
            "azureVoiceMode" => {
                self.settings.azure_voice_mode = if value == "perLanguage" {
                    AzureVoiceMode::PerLanguage
                } else {
                    AzureVoiceMode::Multilingual
                };
            }
            "googleVoiceName" => self.settings.google_voice_name = nonempty(value),
            "googleSpeechRate" => {
                if let Ok(rate) = value.parse::<f64>() {
                    self.settings.google_speech_rate = rate.clamp(-1.0, 1.0);
                }
            }
            "defaultLanguageTag" => {
                self.settings.default_language_tag = value.into();
                self.settings.google_voice_name = None;
            }
            "languageSwitchingEnabled" => {
                self.settings.language_switching_enabled = value == "true"
            }
            _ => return,
        }
        if previous_hotkey != self.settings.hot_key
            && let Some(sender) = &self.shortcut_commands
        {
            let _ = sender.send(shortcuts::Command::Change(self.settings.hot_key));
        }
        self.persist_settings();
    }

    fn apply_route_setting(&mut self, route_id: &str, field: &str, value: &str) {
        let Ok(id) = Uuid::parse_str(route_id) else {
            return;
        };
        if id == DEFAULT_LANGUAGE_ROUTE_ID {
            match field {
                "systemVoiceName" => self.settings.system_voice_name = nonempty(value),
                "systemSpeechRate" => {
                    if let Ok(rate) = value.parse::<f64>() {
                        self.settings.system_speech_rate = rate.clamp(-1.0, 1.0);
                    }
                }
                "azureVoiceName" => self.settings.azure_voice_name = value.into(),
                "azureSpeechRate" => {
                    if let Ok(rate) = value.parse::<f64>() {
                        self.settings.azure_speech_rate = rate.clamp(-1.0, 1.0);
                    }
                }
                "googleVoiceName" => self.settings.google_voice_name = nonempty(value),
                "googleSpeechRate" => {
                    if let Ok(rate) = value.parse::<f64>() {
                        self.settings.google_speech_rate = rate.clamp(-1.0, 1.0);
                    }
                }
                _ => return,
            }
        } else if let Some(route) = self
            .settings
            .language_routes
            .iter_mut()
            .find(|r| r.id == id)
        {
            match field {
                "systemVoiceName" => route.system_voice_name = nonempty(value),
                "systemSpeechRate" => {
                    if let Ok(rate) = value.parse::<f64>() {
                        route.system_speech_rate = rate.clamp(-1.0, 1.0);
                    }
                }
                "azureVoiceName" => route.azure_voice_name = nonempty(value),
                "azureSpeechRate" => {
                    if let Ok(rate) = value.parse::<f64>() {
                        route.azure_speech_rate = rate.clamp(-1.0, 1.0);
                    }
                }
                "googleVoiceName" => route.google_voice_name = nonempty(value),
                "googleSpeechRate" => {
                    if let Ok(rate) = value.parse::<f64>() {
                        route.google_speech_rate = rate.clamp(-1.0, 1.0);
                    }
                }
                _ => return,
            }
        } else {
            return;
        }
        self.persist_settings();
    }

    fn save_azure(&mut self, raw_endpoint: &str, raw_key: &str) {
        let result = azure::normalize_endpoint(raw_endpoint)
            .and_then(|endpoint| azure::validate_key(raw_key).map(|key| (endpoint, key)))
            .and_then(|(endpoint, key)| {
                azure::save_key(&key)?;
                Ok(endpoint)
            });
        match result {
            Ok(endpoint) => {
                self.settings.azure_endpoint = Some(endpoint);
                self.configuration_error = QString::default();
                self.configuration_error_changed();
                self.persist_settings();
                self.load_azure_voices();
            }
            Err(error) => {
                self.configuration_error = error.to_string().into();
                self.configuration_error_changed();
            }
        }
    }

    fn load_azure_voices(&mut self) {
        let Some(endpoint) = self.settings.azure_endpoint.clone() else {
            return;
        };
        self.configuration_error = QString::default();
        self.configuration_error_changed();
        let pointer = QPointer::from(&*self);
        let deliver = queued_callback(move |result: Result<Vec<AzureVoice>, String>| {
            if let Some(backend) = pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                match result {
                    Ok(voices) => {
                        backend.azure_voices = voices;
                        backend.configuration_error = QString::default();
                        backend.configuration_error_changed();
                        backend.refresh_snapshot();
                    }
                    Err(message) => {
                        backend.configuration_error = message.into();
                        backend.configuration_error_changed();
                    }
                }
            }
        });
        std::thread::spawn(move || {
            let result = azure::load_key()
                .and_then(|key| azure::list_voices(&endpoint, &key))
                .map_err(|_| {
                    "Flow could not load Azure voices. Check the endpoint and key.".to_owned()
                });
            deliver(result);
        });
    }

    fn save_google(&mut self, raw_key: &str) {
        let result = google::validate_key(raw_key).and_then(|key| google::save_key(&key));
        match result {
            Ok(()) => {
                self.settings.google_api_key_configured = true;
                self.configuration_error = QString::default();
                self.configuration_error_changed();
                self.persist_settings();
                self.load_google_voices();
            }
            Err(error) => {
                self.configuration_error = error.to_string().into();
                self.configuration_error_changed();
            }
        }
    }

    fn load_google_voices(&mut self) {
        if !self.settings.google_api_key_configured {
            return;
        }
        self.configuration_error = QString::default();
        self.configuration_error_changed();
        let pointer = QPointer::from(&*self);
        let deliver = queued_callback(move |result: Result<Vec<GoogleVoice>, String>| {
            if let Some(backend) = pointer.as_pinned() {
                let mut backend = backend.borrow_mut();
                match result {
                    Ok(voices) => {
                        backend.google_voices = voices;
                        backend.configuration_error = QString::default();
                        backend.configuration_error_changed();
                        backend.refresh_snapshot();
                    }
                    Err(message) => {
                        backend.configuration_error = message.into();
                        backend.configuration_error_changed();
                    }
                }
            }
        });
        std::thread::spawn(move || {
            let result = google::load_key()
                .and_then(|key| google::list_voices(&key))
                .map_err(|_| {
                    "Flow could not load Google voices. Check the API key and confirm that Cloud Text-to-Speech is enabled."
                        .to_owned()
                });
            deliver(result);
        });
    }

    fn persist_settings(&mut self) {
        if settings::save(&self.settings).is_err() {
            self.configuration_error = "Flow could not save its settings.".into();
            self.configuration_error_changed();
        }
        self.refresh_snapshot();
    }

    fn refresh_snapshot(&mut self) {
        self.snapshot_json = serialize(&Snapshot {
            settings: &self.settings,
            supported_languages: language::supported_languages(),
            system_voices: &self.system_voices,
            azure_voices: &self.azure_voices,
            google_voices: &self.google_voices,
        })
        .into();
        self.snapshot_json_changed();
    }

    fn set_state(&mut self, state: PlaybackState) {
        if self.playback_state == state {
            return;
        }
        self.playback_state = state;
        self.state = state.id().into();
        self.state_changed();
    }

    fn set_popup_visible(&mut self, visible: bool) {
        if self.popup_visible == visible {
            return;
        }
        self.popup_visible = visible;
        self.popup_visible_changed();
    }
}

impl Drop for FlowBackend {
    fn drop(&mut self) {
        if let Some(sender) = &self.shortcut_commands {
            let _ = sender.send(shortcuts::Command::Stop);
        }
        if let Some(sender) = &self.system_speech_commands {
            let _ = sender.send(system_speech::Command::Shutdown);
        }
    }
}

fn normalize(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Retains source paragraph breaks without changing the one-code-unit sentence
/// separators used by the Google word-boundary offsets.
fn playback_text(plan: &Plan, source: &str) -> String {
    if plan.sentences.len() < 2 {
        return plan
            .sentences
            .first()
            .map_or_else(|| source.into(), |sentence| sentence.text.clone());
    }

    let mut ranges = Vec::with_capacity(plan.sentences.len());
    let mut search_start = 0;
    for sentence in &plan.sentences {
        let Some(offset) = source[search_start..].find(&sentence.text) else {
            return plan
                .sentences
                .iter()
                .map(|sentence| sentence.text.as_str())
                .collect::<Vec<_>>()
                .join(" ");
        };
        let start = search_start + offset;
        let end = start + sentence.text.len();
        ranges.push(start..end);
        search_start = end;
    }

    let mut text = String::new();
    for (index, sentence) in plan.sentences.iter().enumerate() {
        text.push_str(&sentence.text);
        if index + 1 < plan.sentences.len() {
            let gap = &source[ranges[index].end..ranges[index + 1].start];
            text.push(if gap.matches('\n').count() >= 2 {
                '\n'
            } else {
                ' '
            });
        }
    }
    text
}

fn nonempty(value: &str) -> Option<String> {
    let trimmed = value.trim();
    (!trimmed.is_empty()).then(|| trimmed.to_owned())
}

fn serialize<T: Serialize>(value: &T) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "null".into())
}
